# Generated by Django 5.2 on 2025-04-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='hello', upload_to='user'),
            preserve_default=False,
        ),
    ]
