# Generated by Django 5.0 on 2025-08-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
