# Generated by Django 5.2 on 2025-04-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0004_user_otp_user_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
